### ISSUE TITLE
Thw program crashes randomly on some images

### ISSUE THREAD

**Issue by raghavzns** [Qengineering/Age-Gender-OpenCV-Raspberry-Pi-4#1]
terminate called after throwing an instance of 'cv::Exception'
what (): OpenCV(4.1.2) /home/ns/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 
0 <= roi.width && roi.x + roi.width <=m.cols && roi.y && 0<=roi.height <=m.rows in function 'Mat'

Aborted (core dumped)

**Comment by Qengineering** [comment]
Strange. The face detection outputs beyond the image size.
I've put a simple check at line 86 to prevent any crashes.

```
if(rec.x>=0 && rec.y>=0 && (rec.width+rec.x)<=frame.cols && (rec.height+rec.y)<=frame.rows){
     ......
}
```
